<%@ Page Title="Diamonds Inventory Management" Language="C#" MasterPageFile="~/css/MasterPage_Admin.master"
    AutoEventWireup="true" CodeFile="DiamondsInventoryManagement.aspx.cs" Inherits="www_diamondsInventoryManagement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server" >
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"  style="color: white; font: bold"
        DataSourceID="SqlDataSource1" DataKeyNames="Stone_Name">
        <Columns>
            <asp:BoundField DataField="Stone_Name" HeaderText="Name" SortExpression="Stone_Name" />
            <asp:ImageField DataImageUrlField="Stone_Image" HeaderText="Image">
            </asp:ImageField>
            <asp:BoundField DataField="Stone_Weight" HeaderText="Weight" SortExpression="Stone_Weight" />
            <asp:BoundField DataField="Color_Name" HeaderText="Color" SortExpression="Color_Name" />
            <asp:BoundField DataField="Clarity_Name" HeaderText="Clarity" SortExpression="Clarity_Name" />
            <asp:BoundField DataField="Cut_Name" HeaderText="Cut" SortExpression="Cut_Name" />
            <asp:BoundField DataField="Polish_Name" HeaderText="Polish" SortExpression="Polish_Name" />
            <asp:BoundField DataField="Symmetry_Name" HeaderText="Symmetry" SortExpression="Symmetry_Name" />
            <asp:BoundField DataField="Stone_Cost_P_Discount" HeaderText="Cost P. Discount" SortExpression="Stone_Cost_P_Discount" />
            <asp:BoundField DataField="Stone_T_Cost_Price" HeaderText="T. Cost Price" SortExpression="Stone_T_Cost_Price" />
            <asp:BoundField DataField="Stone_Sale_P_Discount" HeaderText="Sale P. Discount" SortExpression="Stone_Sale_P_Discount" />
            <asp:BoundField DataField="Stone_T_Sale_Price" HeaderText="T. Sale Price" SortExpression="Stone_T_Sale_Price" />
            <asp:BoundField DataField="Status_Name" HeaderText="Status" SortExpression="Status_Name" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DBConnectionString %>"
        SelectCommand="SELECT * FROM [View_DDL]" OldValuesParameterFormatString="original_{0}"
        DeleteCommand="DELETE FROM [dbo].[Stone] WHERE [Stone_Name] = @original_Stone_Name">
        <DeleteParameters>
            <asp:Parameter Name="original_Stone_Name" Type="String" />
        </DeleteParameters>
    </asp:SqlDataSource>
</asp:Content>
